"""Data ingestion helpers for industrial documents."""

from .file_reader import (
    DEFAULT_CHUNK_SIZE,
    FileReadError,
    iter_file_chunks,
    read_file,
    read_text_file,
)
from .models import (
    BlockType,
    BoundingBox,
    DocumentBlock,
    ImageAsset,
    ParsedPage,
    PdfType,
    StructuredDocument,
)
from .ocr import LocalOcrClient, LocalOcrConfig, OcrError
from .parser import (
    CsvParseError,
    DocxParseError,
    ImageParseError,
    SUPPORTED_EXTENSIONS,
    UnsupportedDocumentError,
    XlsxParseError,
    parse_csv,
    parse_document,
    parse_docx,
    parse_image,
    parse_markdown,
    parse_txt,
    parse_xlsx,
)
from .pdf_parser import (
    DEFAULT_VISION_PROMPT,
    IndustrialPdfParser,
    PdfParseError,
    PdfParserConfig,
    parse_pdf,
)
from .reader import DocumentSource
from .vision import (
    ImageDescriber,
    QwenVLClient,
    QwenVLConfig,
    SiliconFlowVisionClient,
    SiliconFlowVisionConfig,
    VisionError,
)

__all__ = [
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_VISION_PROMPT",
    "BlockType",
    "BoundingBox",
    "CsvParseError",
    "DocumentBlock",
    "DocxParseError",
    "DocumentSource",
    "FileReadError",
    "ImageAsset",
    "ImageDescriber",
    "ImageParseError",
    "IndustrialPdfParser",
    "LocalOcrClient",
    "LocalOcrConfig",
    "OcrError",
    "ParsedPage",
    "PdfParseError",
    "PdfParserConfig",
    "PdfType",
    "QwenVLClient",
    "QwenVLConfig",
    "SiliconFlowVisionClient",
    "SiliconFlowVisionConfig",
    "SUPPORTED_EXTENSIONS",
    "StructuredDocument",
    "UnsupportedDocumentError",
    "VisionError",
    "XlsxParseError",
    "iter_file_chunks",
    "parse_csv",
    "parse_docx",
    "parse_document",
    "parse_image",
    "parse_markdown",
    "parse_pdf",
    "parse_txt",
    "parse_xlsx",
    "read_file",
    "read_text_file",
]
